name: Release

on:
  push:
    tags:
      - v*


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  image:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=${GITHUB_REF:11}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Login GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/traptitech/conoha_exporter:${{ env.IMAGE_TAG }}
            ghcr.io/traptitech/conoha_exporter:latest
            